version: '3'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ngcash
    ports:
      - 5433:5432
      
  app:
    image: node:16-alpine
    working_dir: /home/node/app
    restart: always
    depends_on:
      - 'db'
    command: ash -c "yarn && yarn start"
    volumes:
      - ./build:/home/node/app/build/
      - ./.env:/home/node/app/.env
      - ./data/:/home/node/app/data/
      - ./package.json:/home/node/app/package.json
    ports:
      - '3003:3003'
      - '9222:9222'
    links:
      - db
